version: '3'
services:
  dbmysql:
    image: mysql:8.0.21
    container_name: trybe_hotel_db_mysql
    platform: linux/x86_64
    ports:
      - 3308:3306
    environment:
      - MYSQL_ROOT_PASSWORD=123456
    restart: 'always'
